# Generated by Django 3.1.5 on 2021-02-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0002_geeksmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
