# Generated by Django 3.1.5 on 2021-02-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0003_delete_geeksmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('quetion', models.TextField()),
                ('option_one', models.CharField(max_length=50)),
                ('option_two', models.CharField(max_length=50)),
                ('option_three', models.CharField(max_length=50)),
                ('option_four', models.CharField(max_length=50)),
                ('option_one_count', models.IntegerField(default=0)),
                ('option_two_count', models.IntegerField(default=0)),
                ('option_three_count', models.IntegerField(default=0)),
                ('option_four_count', models.IntegerField(default=0)),
            ],
        ),
    ]
