# Generated by Django 2.2.18 on 2021-02-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0004_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='creator_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='votes',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='votes',
            name='img',
            field=models.FileField(default='', upload_to='media'),
        ),
    ]
