# Generated by Django 2.2.18 on 2021-02-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0006_auto_20210211_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
