# Generated by Django 2.2.18 on 2021-02-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0007_auto_20210211_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='img',
            field=models.FileField(default='media', upload_to='media'),
        ),
    ]
